language: java
jdk:
 - oraclejdk8
deploy:
 provider: heroku
 api-key:
  secure: "UJEmkN+K5WFi5IS6lL2KgcA6qkZ3erlvTMz1hqw6h4P9g3IiUPr7wDkqHpIs/z+nxEMTxIfhZhNT6Qdkp0F99RFdXkCZIDTVF4xFrKADJoXcsY5Rr9izIML84jqJoLZOXguKg1kcGgRupvcgHwgAR/KZb/oS8P3U/8abMCgPAvW5a2yMtF11C3MHAgGfRnJS8rJFwqr8gmOyCg02nEEJo5EMZYeg8RY9GqOx3KAzTehq8snMR4I7MFoWqeaEIC1lt/EFHqypdPJtH1Rknb9OAtplx6R/X7OieQWliPTxuzWq/CT/KOqgyOXXDMrfGKJSVUO9jg/BgLV5u4ihWVe5KhvWJKeyGs/HNNBCzuAW+3Yl/IqYH6VUd7NkENYy31o80i7JUbF7Meatj2ZvX/PJra650mn33c17FyLJb1XxPhWYimYw3/UMatLpvLSdGvUsZPCXU8fXCf136PE8/zMwECMRqUPR2UoLNFE+rS91MHSPMBMBrHL1Ym4y+ii3//sm6rZJQADEJlqezNU4guevVUBPNtwBDxKJxd7jr1Uy7jxGFaadJy7/aA8VAzn85sckJjruNTQJ1ewWM7IjaIJjVVgNcSEzSysaFOgvTEmP2DKJ6CcH1+kOwRr5Zlo+zg64ncTNLwXxcvjEU+1lEc2MpZPchP6CP9XjEWrnHKPuvmY="
 app: bettor-league