sudo: required

services:
  - docker
addons:
    apt:
        packages:
            - sshpass

language: java
jdk:
 - oraclejdk8

script:
  - ./mvnw clean install -B

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export IMAGE_NAME=bettor-league-api
  - docker build -t $IMAGE_NAME .
  - docker tag $IMAGE_NAME $DOCKER_USER/$IMAGE_NAME
  - docker push $DOCKER_USER/$IMAGE_NAME
  - sshpass -p $DEPLOY_PASS ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEPLOY_HOST bash /$IMAGE_NAME/start.sh

#deploy:
#  - provider: heroku
#    api-key:
#      secure: "UJEmkN+K5WFi5IS6lL2KgcA6qkZ3erlvTMz1hqw6h4P9g3IiUPr7wDkqHpIs/z+nxEMTxIfhZhNT6Qdkp0F99RFdXkCZIDTVF4xFrKADJoXcsY5Rr9izIML84jqJoLZOXguKg1kcGgRupvcgHwgAR/KZb/oS8P3U/8abMCgPAvW5a2yMtF11C3MHAgGfRnJS8rJFwqr8gmOyCg02nEEJo5EMZYeg8RY9GqOx3KAzTehq8snMR4I7MFoWqeaEIC1lt/EFHqypdPJtH1Rknb9OAtplx6R/X7OieQWliPTxuzWq/CT/KOqgyOXXDMrfGKJSVUO9jg/BgLV5u4ihWVe5KhvWJKeyGs/HNNBCzuAW+3Yl/IqYH6VUd7NkENYy31o80i7JUbF7Meatj2ZvX/PJra650mn33c17FyLJb1XxPhWYimYw3/UMatLpvLSdGvUsZPCXU8fXCf136PE8/zMwECMRqUPR2UoLNFE+rS91MHSPMBMBrHL1Ym4y+ii3//sm6rZJQADEJlqezNU4guevVUBPNtwBDxKJxd7jr1Uy7jxGFaadJy7/aA8VAzn85sckJjruNTQJ1ewWM7IjaIJjVVgNcSEzSysaFOgvTEmP2DKJ6CcH1+kOwRr5Zlo+zg64ncTNLwXxcvjEU+1lEc2MpZPchP6CP9XjEWrnHKPuvmY="
#    app: bettor-league
